[project]
name = "interactive-yt-downloader-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pynput>=1.8.1",
    "questionary>=2.1.0",
    "yt-dlp>=2025.3.31",
]
